---
# - name :  Install mysql
#   hosts: db
#   become: yes
#   ignore_errors: no
#   vars_files:
#     - /home/kas/Рабочий стол/Crieket_lesson/Project/all.yml

#   tasks:

#    - name: update cache
#      apt:
 #       update_cache: yes


    - name: Install MySQL 
      apt: pkg={{ item }}
      with_items:
          - mysql-server
          - python3-mysqldb
          - pip
#      state: presents

    - name: Install PyMySQL using pip
      ansible.builtin.pip:
        name: pymysql
        state: present

    - name: Start and enable MySQL 
      service:
        name: mysql
        state: started
        enabled: yes
    
#      

    - name: Create WordPress db
      mysql_db:
        name: "{{ mysql_db_name }}"
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"
        login_unix_socket: /var/run/mysqld/mysqld.sock
    


    - name: Create WordPress db user
      mysql_user:
        name: "{{ mysql_db_user }}"
        password: "{{ mysql_db_password }}"
        priv: "{{ mysql_db_name }}.*:ALL"
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"
        login_unix_socket: /var/run/mysqld/mysqld.sock
    
    - name: Copy my.cnf to Db
      become: yes
      copy:
        src: /home/kas/Рабочий стол/Crieket_lesson/Project/roles/mysql/templates/my.cnf.j2
        dest: /etc/mysql
