ENV['VAGRANT_SERVER_URL'] = 'https://vagrant.elab.pro'

MACHINES = {
  :inetRouter => {
        :box_name => "centos/8",
        :vm_name => "inetRouter",
        :net => [
                   ["192.168.255.1", 2, "255.255.255.252", "router-net"],
                   ["192.168.255.3", 3, "255.255.255.252", "router-net"],
#                   {adapter: 3, auto_config: false, virtualbox__intnet: "router-net"},
#                   {ip: '192.168.56.10', adapter: 8},
                ]
  },
  :centralRouter => {
        :box_name => "centos/8",
        :vm_name => "centralRouter",
        :net => [
                   ["192.168.255.2", 2, "255.255.255.252", "router-net"],
                   ["192.168.255.4", 3, "255.255.255.252", "router-net"],
#                   {adapter: 3, auto_config: false, virtualbox__intnet: "router-net"},
                   ["192.168.255.9", 6, "255.255.255.252", "office1-central"],
#                   {ip: '192.168.56.11', adapter: 8},
                ]
  },

  :office1Router => {
        :box_name => "centos/8",
        :vm_name => "office1Router",
        :net => [
                   ["192.168.255.10",  2,  "255.255.255.252" , "office1-central"],
                   ["192.168.1.1",     3,  "255.255.255.0",  "vlan1"],
                   ["192.168.1.65",    4,  "255.255.255.0",  "vlan1"],
                   ["192.168.2.1",     5,  "255.255.255.0",  "vlan2"],
                   ["192.168.2.65",    6,  "255.255.255.0",   "vlan2"],
#                   {adapter: 3, auto_config: false, virtualbox__intnet: "vlan1"},
#                   {adapter: 4, auto_config: false, virtualbox__intnet: "vlan1"},
#                   {adapter: 5, auto_config: false, virtualbox__intnet: "vlan2"},
#                   {adapter: 6, auto_config: false, virtualbox__intnet: "vlan2"},
#                   {ip: '192.168.56.20', adapter: 8},
                ]
  },

  :testClient1 => {
        :box_name => "centos/8",
        :vm_name => "testClient1",
        :net => [
                    ["192.168.1.254",   2,  "255.255.255.0",  "vlan1"]
#                   {adapter: 2, auto_config: false, virtualbox__intnet: "testLAN"},
#                   {ip: '192.168.56.21', adapter: 8},
                ]
  },

  :testServer1 => {
        :box_name => "centos/8",
        :vm_name => "testServer1",
        :net => [
                    ["192.168.1.1",   2,  "255.255.255.0",  "vlan1"]
#                   {adapter: 2, auto_config: false, virtualbox__intnet: "testLAN"},
#                   {ip: '192.168.56.22', adapter: 8},
            ]
  },

  :testClient2 => {
        :box_name => "ubuntu/22.04",
        :vm_name => "testClient2",
        :net => [
                    ["192.168.2.254",   2,  "255.255.255.0",  "vlan2"]
#                   {adapter: 2, auto_config: false, virtualbox__intnet: "testLAN"},
#                   {ip: '192.168.56.31', adapter: 8},
                ]
  },

  :testServer2 => {
        :box_name => "ubuntu/22.04",
        :vm_name => "testServer2",
        :net => [
                    ["192.168.2.1",   2,  "255.255.255.0",  "vlan2"]
#                   {adapter: 2, auto_config: false, virtualbox__intnet: "testLAN"},
#                   {ip: '192.168.56.32', adapter: 8},
                ]
  },

}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|
    
    config.vm.define boxname do |box|
   
      box.vm.box = boxconfig[:box_name]
      box.vm.host_name = boxconfig[:vm_name]

      config.vm.provider "virtualbox" do |v|
        v.memory = 1024
        v.cpus = 2
       end

#      if boxconfig[:vm_name] == "testServer2"
#       box.vm.provision "ansible" do |ansible|
#        ansible.playbook = "ansible/provision.yml"
#        ansible.inventory_path = "ansible/hosts"
#        ansible.host_key_checking = "false"
#        ansible.become = "true"
#        ansible.limit = "all"
#       end
#      end

      boxconfig[:net].each do |ipconf|
       box.vm.network("private_network", ip: ipconf[0], adapter: ipconf[1], netmask: ipconf[2], virtualbox__intnet: ipconf[3])
      end

      box.vm.provision "shell", inline: <<-SHELL
        mkdir -p ~root/.ssh
        cp ~vagrant/.ssh/auth* ~root/.ssh
      SHELL
    end
  end
end
