---
- name: Create Prometheus User
  user:
    name: prometheus
    system: yes
    shell: /bin/false

- name: Create Prometheus Directories
  file:
    path: "{{ item }}"
    state: directory
    owner: prometheus
    group: prometheus
  with_items:
    - /etc/prometheus
    - /var/lib/prometheus

- name: Download Prometheus
  unarchive:
    src: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
    dest: /tmp
    remote_src: yes

- name: Install Prometheus Binary
  copy:
    src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/prometheus"
    dest: /usr/local/bin/prometheus
    owner: prometheus
    group: prometheus
    mode: '0755'
    remote_src: yes

- name: Install Prometheus Config
  template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    owner: prometheus
    group: prometheus

- name: Create Prometheus Service
  template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service

- name: Start and Enable Prometheus
  systemd:
    name: prometheus
    state: started
    enabled: yes
    daemon_reload: yes