
BOX_NAME = "ubuntu/22.04"

MACHINES = {
  :nginx => {
    :networks => [
          [ "192.168.1.10",   2, "255.255.255.0", "internal" ],
          [ "192.168.56.10",  8 ]
    ],
  },
  :web1 => {
    :networks => [
          [ "192.168.1.31",  2, "255.255.255.0", "internal" ],
          [ "192.168.56.31", 8 ]
    ],
  },
  :web2 => {
    :networks => [
          [  "192.168.1.32", 2,  "255.255.255.0", "internal" ],
          [  "192.168.56.32",  8 ]
    ],
  },
  :db1 => {
    :networks => [
          [  "192.168.1.41",     2, "255.255.255.0",  "internal"],
          [  "192.168.56.41",  8 ],
    ],
  },
  :db2 => {
    :networks => [
          [ "192.168.1.42",  2, "255.255.255.0", "internal"],
          [ "192.168.56.42",  8 ],
    ],
  },
  :fs => {
    :networks => [
          [ "192.168.1.51",    2, "255.255.255.0", "internal"],
          [ "192.168.56.51",  8 ],
    ],
  },

  :monitor => {
    :networks => [
      [ "192.168.1.61",    2, "255.255.255.0", "internal"],
      [  "192.168.56.61", 8 ],
    ],
  },
}


Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
    config.vm.define boxname do |box|
      box.vm.provider "virtualbox" do |v|
        v.memory = 2000
        v.cpus = 2
      end
      box.vm.box = BOX_NAME
      box.vm.host_name = boxname.to_s

      boxconfig[:networks].each do |ipconf|
        box.vm.network("private_network", ip: ipconf[0], adapter: ipconf[1], netmask: ipconf[2], virtualbox__intnet: ipconf[3])
      end
      
      box.vm.network "forwarded_port", guest: 80, host: 8081, auto_correct: true
      

      box.vm.provision "shell", inline: <<-SHELL
        mkdir -p ~root/.ssh
        cp ~vagrant/.ssh/auth* ~root/.ssh
        sudo sed -i 's/\#PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
        systemctl restart sshd
      SHELL
    end
  end
end

