MACHINES = {
    :web => {
            :box_name => "ubuntu/22.04",
            :ip_addr => '192.168.56.10',
            :memory => 1500,
            :cpus => 2,
    },
    :log => {
        :box_name => "ubuntu/22.04",
        :ip_addr => '192.168.56.15',
        :memory => 1024,
        :cpus => 2,
    }
}
Vagrant.configure("2") do |config|
    MACHINES.each do |boxname, boxconfig|
        config.vm.define boxname do |box|
            box.vm.box = boxconfig[:box_name]
            box.vm.host_name = boxname.to_s
            box.vm.network "private_network", ip: boxconfig[:ip_addr]
            box.vm.provider :virtualbox do |vm|
             vm.memory = boxconfig[:memory]
             vm.cpus = boxconfig[:cpus]
            end
        end
    end
         config.vm.provision "shell",inline: <<-SHELL
            mkdir -p ~root/.ssh
            cp ~vagrant/.ssh/auth* ~root/.ssh
            sudo sed -i 's/\#PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
            systemctl restart sshd
            echo "172.20.10.2" elk >> /etc/hosts
            echo "192.168.56.10" web >> /etc/hosts
            echo "192.168.56.15" log >> /etc/hosts
            SHELL

         config.vm.provision "ansible" do |ansible|
            ansible.playbook = "web.yml"
    end

end
