---
- name: Config centralServer
  hosts: all
  become: true

  tasks:
    - name: Install epel-release
      ansible.builtin.yum:
        name: epel-release

    - name: Install packages
      ansible.builtin.yum:
        name:
          - vim
          - traceroute


    - name: default route
      lineinfile: 
        dest: /etc/sysconfig/network-scripts/ifcfg-eth0
        line: DEFROUTE="no"

    - name: Add default gateway for centralRouter
      lineinfile:
        dest: /etc/sysconfig/network-scripts/ifcfg-eth1
        line: GATEWAY=192.168.0.1 

    - name: Restart network service
      ansible.builtin.systemd:
        name: NetworkManager
        state: restarted

    - name: Restart network service
      ansible.builtin.systemd:
        name: NetworkManager
        state: restarted

    - name: Install nginx
      ansible.builtin.yum:
        name:
          - nginx

    - name: Start and enable nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true