# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|

    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "provision.yml"
        # ansible.inventory_path = "inventory.yml"
        ansible.host_key_checking = "false"
     end
  
     config.vm.define "DynamicWeb" do |vmconfig| 
      vmconfig.vm.box = 'ubuntu/22.04'
      vmconfig.vm.hostname = 'DynamicWeb'
      vmconfig.vm.network "private_network", ip: "192.168.56.10"

      vmconfig.vm.network "forwarded_port", guest: 8083, host: 8083
      vmconfig.vm.network "forwarded_port", guest: 8081, host: 8081
      vmconfig.vm.network "forwarded_port", guest: 8082, host: 8082
      vmconfig.vm.provider "virtualbox" do |vbx|
       vbx.memory = "2048"
       vbx.cpus = "3"
       vbx.customize ["modifyvm", :id, '--audio', 'none']
      end
     end
  
  end